### PR TITLE
Add a desktop-capture demo.

### PR DESCRIPTION
**Pull request by hokein**
A small demo demonstrates the usage of `desktop-capturer` module in Electron. Need to wait atom/electron#2963 gets merged.
desktopcapturer

### CODE REVIEW

**Comment by BigTundra** [comment]
Will this capture the audio from the Mac too.  I read in nwjs that audio only works on windows?

**Comment by hokein** [comment]
@BigTundra  No. The capturer API doesn't capture the audio.

**Comment by sapioit** [comment]
So we might need a way to capture the audio, too, huh?

**Comment by zeke** [comment]
@hokein this is really cool!

**Pull request merged**
